[package]
name = "z-biz-tool-cpu"
version = "0.1.2"
description = "CPU 原理教学模拟器"
edition = "2021"

[lib]
name = "z_biz_tool_cpu_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
